#! /usr/bin/env php 

<?php
use Symfony\Component\Console\Application;
use Tasks\ShowCommand;
use Tasks\AddCommand;
use Tasks\CompleteCommand;
use Tasks\DatabaseAdapter;

require 'vendor/autoload.php';


$app = new Application('Tasks','1.0');


try
{
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch (Exception $exception)
{
    echo $exception->getMessage();
    exit(1);
}

$dbAdapter = new DatabaseAdapter($pdo);

$app->add(new ShowCommand($dbAdapter));

$app->add(new AddCommand($dbAdapter));

$app->add(new CompleteCommand($dbAdapter));

$app->run();

